require:
  - rubocop-rails
  - rubocop-rspec

Bundler/OrderedGems:
  Description: >-
                 Gems within groups in the Gemfile should be alphabetically sorted.
  Enabled: true
  ConsiderPunctuation: true

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "#consistent-string-literals"
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - "app/**/*.rb"

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Metrics/BlockLength:
  Description: "Avoid long blocks with many lines."
  Enabled: true
  Exclude:
    - "config/environments/development.rb"

